### ISSUE TITLE
Error Unmarshal

### ISSUE THREAD

**Issue by agunghimura11** [FadhlanHawali/Digitalent-Kominfo_Introduction-Golang#3]
mohon maaf error seperti ini kira-kira bgmn mas?
![erorr marshal](https://user-images.githubusercontent.com/31621439/95419237-cd924d00-096b-11eb-84d0-ade5131ed4fd.JPG)

**Comment by FadhlanHawali** [comment]
`
[
	{
	"jenis_bangun":"Persegi",
	"panjang":10,
	"lebar":10
	}
]
`

kalau langsung ambil dari github, input nya seperti ini

**Comment by agunghimura11** [comment]
Baik sudah terselesaikan
