### ISSUE TITLE
TUGAS GOLANG - API

### ISSUE THREAD

**Issue by taufikhidayatugmbe03** [FadhlanHawali/Digitalent-Kominfo_Introduction-Golang#4]
Mas, saya mengalami kendala untuk menentukan bangun tersebut kubus atau balok.
Menurut logika saya, jika input panjang, lebar dan tinggi nilainya sama maka bangun tersebut merupakan kubus, jika tidak maka bangun tersebut merupakan balok . Jika benar seperti itu berarti menggunakan percabangan if ya mas?
Pertanyaan saya, bagaimana cara meletakan fungsi if tersebut mas? apakah diletakan pada bagian ini?

type Sisi struct {
	Panjang int `json:"panjang"`
	Lebar   int `json:"lebar"`
	Tinggi  int `json:"tinggi"`
}

type Hasil struct {
	Volume int `json:"volume"`
}

Maaf sebelumnya mas, apakah penggunaan new issues benar untuk seperti ini? hehe

**Comment by FadhlanHawali** [comment]
percabangan if nya kamu bisa letakkan di function baru yang fungsinya buat decide apakah P==L==T, kalau iya berarti return true (kubus), kalau engga berarti return false (balok)

Jadi struct itu hanya murni berisi deklarasi entitas data, tidak memiliki isian logic seperti ituu.

Udah benar mas penggunaan issues nya :+1:

**Comment by taufikhidayat23** [comment]
Baik mas, terimakasih atas penjelasannya 🙏
